server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8084/eureka/
  instance:
    prefer-ip-address: true

springdoc:
  api-docs:
    groups:
      enabled: true
    path: /swagger-doc/v3/api-docs  # Ruta para obtener los OpenAPI docs
  swagger-ui:
    path: /swagger-doc/swagger-ui.html
    urls:
      - url: /person/v3/api-docs  # Ruta que apunta al Swagger de `person-service` a través del Gateway
        name: person-service



management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always

spring:
  cloud:
    gateway:
      routes:
        - id: person-service
          uri:  lb://person-service
          predicates:
            - Path=/person/**
          filters:
            - StripPrefix=1
