server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8084/eureka/
  instance:
    prefer-ip-address: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always

spring:
  cloud:
    gateway:
      routes:
        - id: person-service
          uri:  lb://person-service
          predicates:
            - Path=/person/**
          filters:
            - StripPrefix=1
         # Ruta dinámica para Swagger UI
        - id: swagger-ui-person-service
          uri: lb://person-service  # Usando Eureka para resolver el servicio
          predicates:
            - Path=/person/swagger-ui.html
          filters:
            - RewritePath=/person/swagger-ui.html, /swagger-ui.html

        # Ruta dinámica para las rutas de API Docs (swagger.json)
        - id: swagger-api-docs-person-service
          uri: lb://person-service
          predicates:
            - Path=/person/v3/api-docs/**
          filters:
            - RewritePath=/person/v3/api-docs/(?<segment>.*), /v3/api-docs/${segment}
